apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: benny3644-dev
spec:
  type: ClusterIP  # Change to LoadBalancer if using cloud provider
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql